### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by fk1995** [jtl1207/comic-translation#1]
本地Python版本为3.7.5，话说这种包不先搞个venv么？直接装感觉挺容易遇到这种问题的。

初始化进度 20:034/8  |━━━━━━━━━━          | 50.00% PaddlePaddlePackage部署中...2022-03-16 20:03:20,175 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0> cd C: ;C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\python.exe -m pip install paddlepaddle-gpu==2.2.2 -i https://mirrors.bfsu.edu.cn/pypi/web/simple -f C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\opt/packages --no-index --target C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages --isolated --disable-pip-version-check --cache-dir C:\Users\AERO\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev5\pip_cache --timeout 10 --quiet; echo "---QPT OUTPUT STATUS CODE---" ;$?
ERROR: Could not find a version that satisfies the requirement numpy<=1.19.3,>=1.13; python_version >= "3.5" and platform_system == "Windows" (from paddlepaddle-gpu) (from versions: 1.19.5)
ERROR: No matching distribution found for numpy<=1.19.3,>=1.13; python_version >= "3.5" and platform_system == "Windows"

初始化进度 20:036/8  |━━━━━━━━━━━━━━━     | 75.00% BatchInstallation部署中...Traceback (most recent call last)::
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\run.py", line 25, in <module>
    module.run()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\executor.py", line 470, in run
    self._solve_module()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\executor.py", line 425, in _solve_module
    render()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\executor.py", line 419, in render
    sub_module.unpack()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\modules\base.py", line 202, in unpack
    opt.run(op_path)
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\modules\base.py", line 73, in run
    self.act()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\modules\package.py", line 149, in act
    ready_list = PythonPackages.search_packages_dist_info()[0].keys()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\kernel\qcode.py", line 64, in search_packages_dist_info
    dep_pkg_dict = PythonPackages.search_dep()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\qpt\kernel\qcode.py", line 115, in search_dep
    dep = pkg.requires()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2736, in requires
    dm = self._dep_map
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3032, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3014, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0\Python\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\aero\\downloads\\comic_translation1.1.0.7z\\comic_translation1.1.0\\python\\lib\\site-packages\\torchvision-0.10.1.dist-info\\METADATA'

C:\Users\AERO\Downloads\comic_translation1.1.0.7z\comic_translation1.1.0>pause
Press any key to continue . . .

**Comment by jtl1207** [comment]
整合包不会用电脑上的python的，里面自带了一个python3.8，环境应该是隔离的。
这个错误可能是pip出现问题，但是我测试时没有遇见过。
可以试试将本地的pip也升级至最新版本。
明天我尝试新版打包方法，可以等待更新

**Comment by jtl1207** [comment]
已经确定是本地pip的问题
新版本会处理

**Comment by fk1995** [comment]
1.2.0还是报错：
D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0>"./Python/python.exe" -c "import sys;sys.path.append('./Python');sys.path.append('./Python/Lib');sys.path.append('./Python/Lib/site-packages');sys.path.append('./Python/Scripts');import qpt.run as run"
2022-03-23 00:52:54,987 INFO: QPT Runtime版本号为1.0b3.dev5，若无法使用该程序，可向程序发布者或GitHub: QPT-Family/QPT提 交issue寻求帮助
2022-03-23 00:52:54,991 INFO:
如在本信息之后停留时间较长，请升级Windows Powershell至版本5即可解决该问题，下载地址：
官方地址：https://www.microsoft.com/en-us/download/details.aspx?id=54616
团子云镜像：https://s.dango.cloud/s/GVbhB 下载码：zAkjpradJA2eHiC
2022-03-23 00:52:55,437 INFO: 检测结束，当前Powershell满足使用需求。
2022-03-23 00:52:55,474 INFO:
如在本信息之后停留时间较长，请升级Windows Powershell至版本5即可解决该问题，下载地址：
官方地址：https://www.microsoft.com/en-us/download/details.aspx?id=54616
团子云镜像：https://s.dango.cloud/s/GVbhB 下载码：zAkjpradJA2eHiC
2022-03-23 00:52:55,894 INFO: 检测结束，当前Powershell满足使用需求。
2022-03-23 00:52:55,904 INFO: 初次使用将会适应本地环境，可能需要几分钟时间，请耐心等待...
初始化进度 00:524/8  |━━━━━━━━━━          | 50.00% PaddlePaddlePackage部署中...2022-03-23 00:52:58,684 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0> cd D: ;D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0\Python\python.exe -m pip install paddlepaddle-gpu==2.2.2 -i https://mirrors.bfsu.edu.cn/pypi/web/simple -f D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0\opt/packages --no-index --target D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0\Python\Lib\site-packages --isolated --disable-pip-version-check --cache-dir C:\Users\AERO\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev5\pip_cache --timeout 10 --quiet; echo "---QPT OUTPUT STATUS CODE---" ;$?
ERROR: Could not find a version that satisfies the requirement numpy<=1.19.3,>=1.13; python_version >= "3.5" and platform_system == "Windows" (from paddlepaddle-gpu) (from versions: 1.19.5)
ERROR: No matching distribution found for numpy<=1.19.3,>=1.13; python_version >= "3.5" and platform_system == "Windows"

初始化进度 00:525/8  |━━━━━━━━━━━━        | 62.50% AutoRequirementsPackage部署中...2022-03-23 00:53:00,404 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0> cd D: ;D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0\Python\python.exe -m pip install -r C:\Users\AERO\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev5\Cache\FileSerialize.tmp -i https://mirrors.bfsu.edu.cn/pypi/web/simple -f D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0\opt/packages --no-index --target D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0\Python\Lib\site-packages --isolated --disable-pip-version-check --cache-dir C:\Users\AERO\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev5\pip_cache --timeout 10 --quiet; echo "---QPT OUTPUT STATUS CODE---" ;$?
ERROR: Could not find a version that satisfies the requirement unidic-lite==1.0.8 (from versions: none)
ERROR: No matching distribution found for unidic-lite==1.0.8

初始化进度 00:536/8  |━━━━━━━━━━━━━━━     | 75.00% BatchInstallation部署中...2022-03-23 00:53:00,799 INFO: 需要补充的安 装包数量为：89
2022-03-23 00:53:01,825 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0> cd D: ;D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0\Python\python.exe -m pip install bce -i https://mirrors.bfsu.edu.cn/pypi/web/simple --no-deps -f D:\cowtransfer\comic_translation1.2.0.7z\comic_translation1.2.0\opt/packages --no-index --isolated --disable-pip-version-check --cache-dir C:\Users\AERO\AppData\Local\Temp\QPT_Cache_V/1.0b3.dev5\pip_cache --timeout 10 --quiet; echo "---QPT OUTPUT STATUS CODE---" ;$?
ERROR: Could not find a version that satisfies the requirement bce (from versions: python-sdk-0.8.64)
ERROR: No matching distribution found for bce

**Comment by jtl1207** [comment]
【第一次打开会安装虚拟环境，需要7分钟，安装结束有报错没有关系(4个)。】
我在说明里写了。。。这个没关系的，1.2.0是正常安装

numpy  ，unidic-lite， python-sdk，Levenshtein这4个报错没有关系。
整合包第一次部署时会安装python库和环境，这个安装是一次性的，关闭以后再次打开也无法安装，需要还原opt文件夹
