### ISSUE TITLE
Program execution error

### ISSUE THREAD

**Issue by xxzidane12** [jtl1207/comic-translation#11]
Hi,

I get following error when execute

```
Traceback (most recent call last):
  File "C:\Users\User\Downloads\comic_translation1.2.1\Python\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Users\User\Downloads\comic_translation1.2.1\Python\lib\collections\__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Users\User\Downloads\comic_translation1.2.1\Python\lib\collections\__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'word_mod'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\Downloads\comic_translation1.2.1\resources\main.py", line 971, in config_read
    self.var.word_mod = config.get('var', 'word_mod')
  File "C:\Users\User\Downloads\comic_translation1.2.1\Python\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'word_mod' in section: 'var'
```

Please assist

**Comment by jtl1207** [comment]
You can try to download the config.ini file again [config.ini](https://github.com/jtl1207/comic-translation/blob/main/config.ini)
