### ISSUE TITLE
opencv安装过程缺失配置文件

### ISSUE THREAD

**Issue by TwilightHome20** [jtl1207/comic-translation#14]
手动安装paddlepaddle_gpu不再报错,开始提示opencv配置文件丢失
2022-11-23 00:50:44,976 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1> cd "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\resources";./../Python/python.exe "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\resources\main.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
File "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\resources\main.py", line 11, in
import cv2
File "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\Python\Lib\site-packages\cv2_init_.py", line 188, in
bootstrap()
File "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\Python\Lib\site-packages\cv2_init_.py", line 118, in bootstrap
load_first_config(['config.py'], True)
File "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\Python\Lib\site-packages\cv2_init_.py", line 116, in load_first_config
raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.ns: 1.19.5)
ERROR: No matching distribution found for numpy<=1.19.3,>=1.13; python_version >= "3.5" and platform_system == "Windows"

**Comment by TwilightHome20** [comment]
或许是因为环境是anaconda而不是python?

**Comment by TwilightHome20** [comment]
手动安装paddlepaddle_gpu不再报错,开始提示opencv配置文件丢失
2022-11-23 00:50:44,976 ERROR: 在执行终端命令时检测到了失败，完整信息如下：
PS C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1> cd "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\resources";./../Python/python.exe "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\resources\main.py" ; echo "---QPT OUTPUT STATUS CODE---" $?
Traceback (most recent call last):
  File "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\resources\main.py", line 11, in <module>
    import cv2
  File "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\Python\Lib\site-packages\cv2\__init__.py", line 188, in <module>
    bootstrap()
  File "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\Python\Lib\site-packages\cv2\__init__.py", line 118, in bootstrap
    load_first_config(['config.py'], True)
  File "C:\Users\Twilight\Desktop\comic_translation1.2.1\comic_translation1.2.1\Python\Lib\site-packages\cv2\__init__.py", line 116, in load_first_config
    raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.

**Comment by TwilightHome20** [comment]
> 

wow,可以使用了,谢谢大佬,顺便想问一下翻译文本框的聚焦和相应功能按钮有快捷键吗?

**Comment by jtl1207** [comment]
最近好久都没空更新，沉迷赚钱.jpg  这些功能可能要好久之后了
