### ISSUE TITLE
1.2.0 version error..

### ISSUE THREAD

**Issue by kdrkdrkdr** [jtl1207/comic-translation#6]
![image](https://user-images.githubusercontent.com/49074597/159480913-f0c767f8-486d-4add-ae5d-eff5c85a48af.png)

Traceback (most recent call last):
  File "C:\Users\power\Desktop\comic_translation1.2.0\resources\main.py", line 168, in <lambda>
    self.ui.pushButton_5.clicked.connect(lambda event: self.doit())
  File "C:\Users\power\Desktop\comic_translation1.2.0\resources\main.py", line 646, in doit
    self.do_translation()
  File "C:\Users\power\Desktop\comic_translation1.2.0\resources\main.py", line 680, in do_translation
    self.memory.img_show = img.copy()
AttributeError: 'Render' object has no attribute 'copy'

I clicked button to edit text.. but not works..

**Comment by jtl1207** [comment]
You can open the .\resources\main file with notepad
Change img.copy() on line 680 to img

I tested and didn't find this problem.
copy() just uses a little more memory, and deleting it is not guaranteed to work.
It may be caused by the wrong installation of 'pil', or it may be caused by an incorrect font.

You can try changing the font test, you can try malgun.ttf from C:\Windows\Fonts

**Comment by kdrkdrkdr** [comment]
It works! thanks!
